<?php
$mess=array(
"insurancecomplete" => "<span style='color:green;'>Your are Insurance request sent successfully.</span>",
"loancomplete" =>  "<span style='color:green;'>Your are loan request sent successfully.</span>",
"login"=>"<span style='color:green;'>You are logged in successfully.</span>",
"del"=>"<span style='color:green;'>Record has been deleted successfully.</span>",
"multidel"=>"<span style='color:green;'>Selected records has been deleted successfully.</span>",
"multiact"=>"<span style='color:green;'>Selected records has been activated successfully.</span>",
"multiinact"=>"<span style='color:green;'>Selected records has been deactivated successfully.</span>",
"add"=>"<span style='color:green;'>Record has been inserted successfully.</span>",
"edit"=>"<span style='color:green;'>Record has been updated successfully.</span>",
"deactive"=>"<span style='color:green;'>Record has been deactivated successfully.</span>",

"reject"=>"<span style='color:green;'>Record has been reject successfully.</span>",
"approve"=>"Record has been approve successfully.",

"featured"=>"Record has been featured successfully.",
"unfeatured"=>"<span style='color:green;'>Record has been unfeatured successfully.</span>",
"tillinactive"=>"<span style='color:red;'>Your account is inactive. Please contact the administrator <a href='".SITE_URL."/contact-us'>here</a>.</span>",


"Advertisement"=>"<span style='color:green;'>Your inquiry for advertisement has been successfully submitted.</span>",

"commentsadd"=>"Your Comment added successfully.",
"commentprob"=>"Probleme in comment added.",
"moreadd"=>"Please add other information also.",

"reservations"=>"Your Reservations has been successfully done.",
"listexists"=>"Entered list already exists.",
"eventexists"=>"Event already booked.",
"eventbook"=>"Event booked successfully.",
"eventAdd"=>"Event added successfully.",
"profileupdate"=>"Your profile updated successfully.",


"pending"=>"<span style='color:green;'>Record has been Cancled successfully.</span>",
"pendding"=>"<span style='color:green;'>Record has been Cancled successfully.</span>",
"logout"=>"<span style='color:green;'>You are logged out successfully.</span>",
"nameexists"=>"Entered Name already exists.",
"urlexists"=>"Entered Url already exists.",
"emailexists"=>"Entered Email already exists.",
"couponexists"=>"Entered Coupon already exists.",
"passwordmismatch"=>"You have entered wrong password in current password field.",
"invalid"=>"<span style='color:red;'>Invalid Email/Password</span>",
"invaliduser"=>"<span style='color:red;'>Username does not exists. Please Try Again</span>",
"editinfo"=>"Your details has been changed successfully.",
"chgstus"=>"Content has been publised successfully!!",
"restore"=>"The page was restored successfully.",
"order"=>"Menu Items Reordered Successfully!!",
"newssent"=>"Newsletter has been sent successfully!!",
"error"=>"<span style='color:red;'>Error Occured! Mail has not been sent!</span>",
"sessionexpire"=>"Your session has been expire! Please login agint to access Admin.",
"filedel"=>"File has been Removed!",
"logfirst"=>"<span style='color:red;'>Please, Login first!</span>",
"nochpass"=>"<span style='color:red;'>You have entered wrong password. Please Try Again</span>",
"chpass"=>"Your password has been changed successfully!!",
"setsave"=>"Settings has been changed successfully!",
"newssend"=>"Newsletter has been sent to subscribe users.",
"sameuser"=>"<span style='color:red;'>User name already exist!!</span>",
"reg"=>"You have successfully registered to our site.",
"loginfirst"=>"<span style='color:red;'>Please, Login First !!</span>",
"passsent"=>"Your Password has been sent to your email address.",
"chkpasssemail"=>"Please check your mail to reset your password.",
"emailnotexist"=>"<span style='color:red;'>The E-Mail address you have entered does not exist. Please try again.</span>",
"emailsent"=>"Thank you! Your enquiry has been sent to administrator",
"orsentdel"=>"Order has been sent! member info has been deleted from database.",
"reviewadd"=>"Thank You! Your review has been submitted.",

"reviewsend"=>"Your review has been send successfully.",

"csvuploaded"=>"Order CSV uploaded successfully!!",
"csvexported"=>"CSV exported successfully!!",
"csverror" =>"Error in CSV export!!",
"addimg"=>"Image uploaded successfully!!",
"delimg"=>"Image deleted successfully!!",
"active"=>"<span style='color:green;'>Record has been activated successfully.</span>",
"confirm"=>"<span style='color:green;'>Record has been confirmed.</span>",
"imageonly"=>"<span style='color:red;'>Please upload image only</span>",
"sameemail"=>"<span style='color:red;'>Email address already exists</span>",
"userinactive"=>"<span style='color:red;'>User has been deactivated successfully.</span>",
"useractivated"=>"<span style='color:red;'>User has been activated successfully.</span>",
"alreadyactivated"=>"<span style='color:red;'>Your account Already Activated.</span>",
"invalidConfirmation"=>"<span style='color:red;'>Please Check Your Mail For Correct Activation link.</span>",
"chkLink"=>"<span style='color:red;'>Please Check Your Mail For Correct link.</span>",
"queexist"=>"<span style='color:red;'>Question already exists.</span>",
"alreadybookmarked"=>"You have already saved this article in your list",
"bookmarksaved"=>"Article has been saved to your list",
"inqsent"=>"Your inquiry has been sent to us. We will contact you as soon as possible.",
"artsub"=>"Thank you! Your article has been submitted successfully! Once Admin will approve your article, it will be list into site.",
"invsent"=>"Invitation sent successfully.",
"ratesucc"=>"Thanks for your rating!",
"commentsucc"=>"Thanks For your comments. Once administrator will approve your comment, it will display on site",
"reportAdd"=>"Thank you! Your report has been submitted successfully.",
"frdexist"=>"You have already added this user as a friend.",
"frdadded"=>"You have successfully added this user as a Friend.",
"itsyou"=>"You can't add yourself as a Friend.",
"required"=>"<span style='color:red;'>Please enter all fields.</span>",
"subscribesuccess"=>"You have successfully subscribed to our newsletter.",
"alreadysubscribed"=>"You are already registered.",
"permissiondenied"=>"You have not access permission.",
"norecode"=>"Recode not found.",
"selectone"=>"Please Select Only one Resource.",
"notavailable"=>"<span style='color:red;'>Email already in use, please try another.</span>",
"sentfriend"=>"<span style='color:green;'>Mail has been successfully sent to your friends.</span>",
"careerinq"=>"<span style='color:green;'>Your application has been successfully submitted.</span>",
"ReviewAdd"=>"Your Review Successfully Submitted, It will Display After Administrator's Approval, Thanks!.",
"errorSubmit"=>"<span style='color:red;'>Error Occured!</span>",

"filesizeBig"=>"The Size of uploded file is to big.",
"invalidFormat"=>"Invalid file formate!.. Please Upload a valid file",
"ipBan"=>" Your Ip is Temporary Ban, Please Try After Some Time",
"notAllow"=>"<span style='color:red;'>Sorry, You Don't Delete The Parent Records</span>",
"feedback"=>"<span style='color:red;'>Thank you for your feedback</span>",
"invalidtoken" => "<span style='color:red;'>Invalid Token, Try Again.</span>",
"useradded"=>"User account added successfully.",
"userchanged"=>"Your account has been updated successfully.",
"userdel"=>"<span style='color:green;'>User account has been deleted successfully.</span>",
"usermultidel"=>"<span style='color:green;'>Users account has been deleted successfully.</span>",
"payment_success"=>"<span style='color:green;'>Congratulations! Your payment has been successfully submitted.</span>",
"maximum"=>"<span style='color:green;'>You can not invite more than 9 friends!</span>",
"updatesubscription"=>"Your subscription has been updated successfully.",

);
?>